#!/usr/bin/with-contenv bash

# If config file exists, start daemon
if [ -f /etc/frr/ospfd.conf ] ; then
    echo "Starting FRRouting (ospfd)"

    exec \
        /usr/lib/frr/ospfd
else
    # Otherwise sleep for a while...
    sleep 60
fi
