#!/usr/bin/with-contenv bash

# If config file exists, start daemon
if [ -f /etc/frr/ripd.conf ] ; then
    echo "Starting FRRouting (ripd)"

    exec \
        /usr/lib/frr/ripd
else
    # Otherwise sleep for a while...
    sleep 60
fi
