#!/usr/bin/with-contenv bash

# If config file exists, start daemon
if [ -f /etc/frr/zebra.conf ] ; then
    echo "Starting FRRouting (zebra)"

    exec \
        /usr/lib/frr/zebra
else
    # Otherwise sleep for a while...
    sleep 60
fi
