#!/usr/bin/with-contenv bash

# If config file exists, start daemon
if [ -f /etc/frr/isisd.conf ] ; then
    echo "Starting FRRouting (isisd)"

    exec \
        /usr/lib/frr/isisd
else
    # Otherwise sleep for a while...
    sleep 60
fi
