#!/usr/bin/with-contenv bash

# If config file exists, start daemon
if [ -f /etc/frr/bgpd.conf ] ; then
    echo "Starting FRRouting (bgpd)"

    exec \
        /usr/lib/frr/bgpd
else
    # Otherwise sleep for a while...
    sleep 60
fi
